#!/bin/sh

# set variable names
userresources=$DOTFILES/x11/xresources
usermodmap=$DOTFILES/x11/xmodmap
userprofile=$DOTFILES/x11/xprofile

# default xinit scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# user init scripts and settings
[ -f $usermodmap ] && xmodmap $usermodmap
[ -f $userresources ] && xrdb -merge $userresources
[ -f $userprofile ] && . $userprofile

# keyrepeat settings
xset r rate 200 50

# start window manager
exec i3 &> /dev/null
