# vim:ft=zsh
# Filename: aliases
#
# Sourced By: ZSH
# Symlink To: $ZSH/.zshrc
#
# Purpose:

[ -f $ZSH/aliases ] && source $ZSH/aliases
[ -f $ZSH/prompt ] && source $ZSH/prompt
[ -f $ZPLUG_HOME/init.zsh ] && source $ZPLUG_HOME/init.zsh
[ -f $ZSH/anaconda3 ] && source $ZSH/anaconda3

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
zplug "plugins/history-substring-search", from:oh-my-zsh

if ! zplug check; then
    zplug install
fi

zplug load
